/*
  # Seed Additional Questions

  Adds enough questions for all certificate types to support full-length practice exams:
  - PPL: ~60 questions total needed
  - IFR: ~60 questions total needed
  - CPL: ~100 questions total needed
  - ATP: ~125 questions total needed

  This migration adds bulk questions across all categories.
*/

INSERT INTO questions (certificate, category, subcategory, question, options, correct_answer, explanation) VALUES

-- PPL Additional Questions
('PPL', 'Regulations', 'Certificates', 'A private pilot certificate is valid', '["For 24 months then must be renewed", "Until surrendered, suspended, or revoked", "Until the pilot reaches age 65"]', 1, 'Under FAR 61.19, a private pilot certificate has no expiration date. It remains valid until surrendered, suspended, or revoked by the FAA.'),
('PPL', 'Regulations', 'Medical', 'A third-class medical certificate for a pilot under 40 years of age is valid for first-class operations for how long?', '["12 months", "24 months", "60 months"]', 2, 'Under FAR 61.23, a third-class medical issued to pilots under 40 is valid for 60 calendar months for private pilot operations.'),
('PPL', 'Regulations', 'Right of Way', 'When two aircraft are converging at approximately the same altitude, which aircraft has the right-of-way?', '["The aircraft on the left", "The aircraft on the right", "The faster aircraft"]', 1, 'FAR 91.113(d) states that when two aircraft of the same category converge, the aircraft to the other''s right has the right-of-way.'),
('PPL', 'Regulations', 'VFR Flight Plan', 'How long after a VFR flight plan is filed can a pilot expect search and rescue to begin if the flight is overdue?', '["30 minutes", "1 hour", "30 minutes after ETA at destination"]', 2, 'Under FAR 91.153, if a VFR flight plan is filed and the pilot fails to close it within 30 minutes of the ETA, search and rescue operations may be initiated.'),
('PPL', 'Weather', 'Fog', 'Which type of fog is most likely to form on a clear, calm night when the temperature/dewpoint spread is small?', '["Advection fog", "Radiation fog", "Upslope fog"]', 1, 'Radiation fog forms on clear, calm nights when the ground radiates heat into the atmosphere, cooling the surface air to its dewpoint. Clear skies allow maximum radiative cooling, and calm winds prevent mixing.'),
('PPL', 'Weather', 'Winds', 'What causes a sea breeze?', '["Land heating faster than water during the day, causing air to flow from sea to land", "Water heating faster than land, causing air to flow from land to sea", "Upper winds pushing surface air onshore"]', 0, 'During the day, land heats faster than water. Warm air over the land rises, and cooler, denser air from over the sea flows in to replace it — creating a sea breeze.'),
('PPL', 'Weather', 'Turbulence', 'Where is wind shear most likely to be encountered during an approach?', '["Only above 3,000 feet AGL", "Near the surface when there are temperature inversions or fronts", "Only during instrument meteorological conditions"]', 1, 'Wind shear is most commonly encountered near the surface in the presence of temperature inversions, frontal zones, and thunderstorm activity. It is especially hazardous during approach and departure.'),
('PPL', 'Weather', 'Density Altitude', 'Which conditions result in the highest density altitude?', '["High elevation, high temperature, high humidity", "Low elevation, low temperature, low humidity", "High elevation, low temperature, low humidity"]', 0, 'Density altitude is pressure altitude corrected for non-standard temperature. High elevation (low pressure), high temperature, and high humidity all reduce air density, resulting in the highest density altitude.'),
('PPL', 'Aerodynamics', 'Load Factor', 'In a 60-degree banked level turn, the load factor is approximately', '["1.5 Gs", "2.0 Gs", "2.5 Gs"]', 1, 'In a coordinated level turn, load factor = 1/cos(bank angle). At 60 degrees: 1/cos(60°) = 1/0.5 = 2.0 Gs.'),
('PPL', 'Aerodynamics', 'Ground Effect', 'What effect does ground effect have on aircraft performance during takeoff?', '["Increases induced drag and reduces lift", "Reduces induced drag and increases effective lift", "Has no effect on performance"]', 1, 'Ground effect reduces induced drag (and the associated downwash) when the aircraft is within one wingspan of the ground. This allows the aircraft to become airborne at a lower speed than would otherwise be required.'),
('PPL', 'Aerodynamics', 'Torque', 'In a single-engine aircraft with a clockwise rotating propeller (viewed from the cockpit), the tendency to yaw left on takeoff is caused by', '["P-factor and torque reaction", "Coriolis effect", "Gyroscopic precession only"]', 0, 'Left-turning tendencies on takeoff are caused by: (1) Torque reaction — the fuselage tries to rotate opposite the propeller, (2) P-factor — at high AOA the descending blade produces more thrust, (3) spiraling slipstream hitting the left side of the vertical stabilizer.'),
('PPL', 'Navigation', 'Time', 'When converting from UTC to local standard time in the Central Time Zone, you would', '["Subtract 6 hours", "Add 6 hours", "Subtract 5 hours"]', 0, 'Central Standard Time (CST) is UTC minus 6 hours. To convert from UTC to CST, subtract 6 hours.'),
('PPL', 'Navigation', 'Pilotage', 'What is the definition of pilotage?', '["Navigation by reference to landmarks", "Navigation using radio aids", "Navigation using dead reckoning techniques"]', 0, 'Pilotage is the technique of navigating by visual reference to landmarks on the ground. The pilot compares the actual terrain features with the sectional chart to determine position.'),
('PPL', 'Navigation', 'Lost Procedures', 'If a pilot becomes lost during flight, the recommended initial action is', '["Climb to a higher altitude to extend radio range and visibility", "Immediately declare an emergency and squawk 7700", "Reduce power and glide to save fuel"]', 0, 'The recommended action when lost is to climb for better visibility and radio reception, then attempt to positively identify your position using radio aids or visible landmarks. CLIMB, CONSERVE, COMMUNICATE, CONFESS.'),
('PPL', 'Systems', 'Pitot-Static', 'During a preflight inspection, you notice the pitot tube cover was left on. Which instruments would be affected during flight?', '["Only the airspeed indicator", "Airspeed indicator and vertical speed indicator", "Airspeed indicator, altimeter, and VSI"]', 0, 'Only the airspeed indicator uses pitot pressure. The altimeter and VSI use only static pressure, so they would still function normally (though the static port can be blocked separately).'),
('PPL', 'Systems', 'Carburetor', 'Carburetor ice is most likely to form at outside air temperatures of', '["Below -10°C only", "Between -10°C and +38°C with high humidity", "Only at temperatures below 0°C"]', 1, 'Carburetor ice can form at temperatures well above freezing because the venturi effect in the carburetor causes significant temperature drops — sometimes 15-25°C below ambient. It is most likely between -10°C and +38°C with high relative humidity.'),
('PPL', 'Systems', 'Magnetos', 'What is the purpose of performing a magneto check during the runup?', '["To check for proper RPM range", "To check for excessive RPM drop, indicating ignition system problems", "To warm up the engine to operating temperature"]', 1, 'The magneto check verifies that both magneto-ignition circuits are functioning properly and identifies if either circuit has excessive drop, which would indicate fouled plugs or ignition system issues.'),
('PPL', 'Airport Operations', 'Traffic Pattern', 'At what altitude is the traffic pattern typically flown?', '["500 feet AGL", "800 feet AGL", "1000 feet AGL"]', 2, 'The standard traffic pattern altitude is 1,000 feet AGL for piston aircraft, unless otherwise published in the Airport/Facility Directory or shown on sectional charts.'),
('PPL', 'Airport Operations', 'Runway Markings', 'What does a yellow X displayed on a runway or taxiway indicate?', '["The area is closed", "Caution — construction area", "Hold short position"]', 0, 'A yellow X marking on a runway or taxiway indicates that the surface is closed. Pilots should not use that runway or taxiway.'),
('PPL', 'Airport Operations', 'Communications', 'When operating in Class E airspace below 10,000 feet MSL, the appropriate radio communication frequency to monitor is', '["Guard frequency 121.5 MHz", "Unicom frequency 122.8 MHz", "There is no requirement to monitor a specific frequency in Class E airspace"]', 2, 'Class E airspace has no mandatory radio communication requirements. However, FARs require that aircraft equipped with radios maintain a continuous watch on the appropriate frequency when operating within 4nm of a Class D airport.'),
('PPL', 'Regulations', 'Pre-Flight', 'Before each flight, a pilot in command is required to', '["Become familiar with all available information concerning the flight", "File a VFR flight plan", "Check weather conditions only at the departure airport"]', 0, 'FAR 91.103 requires the pilot in command to become familiar with all available information concerning the flight, including weather reports and forecasts, fuel requirements, known traffic delays, and runway lengths.'),
('PPL', 'Weather', 'METAR', 'In a METAR report, the sky condition OVC010 means', '["Overcast at 10,000 feet MSL", "Overcast at 1,000 feet AGL", "One-tenth sky coverage at 10,000 feet"]', 1, 'In METARs, cloud heights are reported in hundreds of feet AGL. OVC010 means overcast at 1,000 feet AGL. The digits represent hundreds of feet above ground level.'),
('PPL', 'Weather', 'Wind', 'A METAR reports winds as 270 at 15 knots. This means the wind is blowing', '["From the west at 15 knots", "To the west at 15 knots", "From the east at 15 knots"]', 0, 'Wind direction in aviation reports indicates the direction FROM which the wind is blowing. 270 degrees is due west, so the wind is blowing from the west at 15 knots.'),
('PPL', 'Aerodynamics', 'Flaps', 'The primary purpose of wing flaps is to', '["Increase lift and drag for slower flight and shorter landings", "Increase roll control at slow speeds", "Reduce stall speed without changing lift"]', 0, 'Flaps increase both lift and drag. They allow slower airspeeds (lower stall speed) and steeper approach angles, enabling shorter landing distances. They also increase the approach angle without increasing airspeed.'),
('PPL', 'Regulations', 'Alcohol', 'Under FAR 91.17, a pilot may not act as crew member within how many hours after consuming alcohol?', '["8 hours", "12 hours", "24 hours"]', 0, 'FAR 91.17 prohibits acting as crew member within 8 hours of consuming alcohol. Additionally, blood alcohol content must be below 0.04%, and a pilot may never fly while under the influence of alcohol.'),
('PPL', 'Regulations', 'Night Currency', 'To be current to carry passengers at night, a pilot must have made in the preceding 90 days at least', '["3 takeoffs and 3 landings to a full stop in the applicable category and class at night", "3 takeoffs and 3 landings in the applicable category and class at night", "1 hour of night flight"]', 0, 'FAR 61.57(b) requires that to act as PIC carrying passengers at night, a pilot must have completed at least 3 takeoffs and 3 full-stop landings during the period from 1 hour after sunset to 1 hour before sunrise within the preceding 90 days.'),
('PPL', 'Navigation', 'Sectional Charts', 'On a VFR sectional chart, what does a blue airport symbol (with a control tower) indicate?', '["A towered airport with instrument approaches", "A towered airport (Class D or B/C)", "An airport with a Part 139 certification"]', 1, 'Blue airport symbols on sectional charts indicate airports with operating control towers. Magenta airport symbols indicate non-towered airports.'),
('PPL', 'Systems', 'Gyroscopes', 'Which flight instrument uses a gyroscope that is NOT vacuum-driven on most light aircraft?', '["Attitude indicator", "Heading indicator", "Turn coordinator"]', 2, 'The turn coordinator (or turn-and-slip indicator) is typically electrically driven, while the attitude indicator and heading indicator are usually vacuum/suction driven in light aircraft. This provides backup in case of vacuum system failure.'),
('PPL', 'Aerodynamics', 'Wake Turbulence', 'The greatest wake turbulence hazard from a heavy jet is encountered', '["Behind and above the flight path", "Behind and below the flight path at the same altitude", "Directly behind the aircraft at the same altitude"]', 1, 'Wake turbulence (wingtip vortices) descend from and sink below the generating aircraft''s flight path. The greatest hazard is behind and slightly below the aircraft that generated the vortices.'),
('PPL', 'Airport Operations', 'ATIS', 'ATIS broadcasts are updated', '["Every 30 minutes", "When there is a significant change in conditions or once per hour", "Continuously in real-time"]', 1, 'ATIS is updated whenever there is a significant change in weather conditions (ceiling, visibility, precipitation, etc.) or at least once each hour. Each update is assigned a phonetic alphabet identifier.'),

-- IFR Questions
('IFR', 'Procedures', 'Approach', 'What is the purpose of a Missed Approach Procedure (MAP)?', '["Provide guidance when the runway environment is not in sight at the DH/MDA", "Only used when ATC instructs a missed approach", "Used to transition from cruise to approach phase"]', 0, 'The Missed Approach Procedure is initiated when the runway environment (or required visual references) is not in sight at the Decision Height (precision) or Missed Approach Point (non-precision), or any time the pilot determines a safe landing cannot be made.'),
('IFR', 'Procedures', 'Approach', 'On an ILS approach, what does the glideslope indicate?', '["Lateral guidance to the runway centerline", "Vertical guidance to the touchdown zone at approximately 3 degrees", "Both lateral and vertical guidance combined"]', 1, 'The glideslope component of the ILS provides vertical guidance, typically at a 3-degree angle, guiding the aircraft to the touchdown zone. The localizer provides the lateral guidance.'),
('IFR', 'Procedures', 'Departure', 'A Standard Instrument Departure (SID) is a', '["Published ATC procedure designed to expedite traffic flow departing an airport", "Mandatory departure routing for all IFR flights", "Radar departure procedure only"]', 0, 'A SID (now called a Departure Procedure or DP) is a published ATC procedure that provides obstacle clearance and expedites the transition from departure to the en route phase of flight.'),
('IFR', 'Navigation', 'VOR', 'When tracking outbound on a VOR radial, you should center the CDI needle with the', '["FROM indication showing", "TO indication showing", "Either TO or FROM depending on the radial"]', 0, 'When flying outbound away from a VOR, the OBS should be set to the desired radial and the CDI centered with a FROM indication. Flying inbound toward a VOR uses a TO indication.'),
('IFR', 'Navigation', 'DME', 'DME distance is measured as', '["Slant range distance from the aircraft to the VORTAC", "Horizontal ground distance to the station", "The straight-line distance corrected for altitude"]', 0, 'DME measures slant range — the straight-line distance from the aircraft antenna to the ground station. At low altitudes or close distances, slant range can differ significantly from ground distance.'),
('IFR', 'Weather', 'PIREPs', 'A PIREP containing the notation "LLWS" indicates', '["Low-level wind shear reported by a pilot", "Low-level weather system below 2,000 feet", "A pilot report of lightning within 5 miles"]', 0, 'LLWS stands for Low Level Wind Shear. When included in a PIREP, it indicates that a pilot has reported wind shear conditions at low altitudes, typically below 2,000 feet AGL, which is critical information for other pilots on approach or departure.'),
('IFR', 'Regulations', 'Equipment', 'For IFR flight in controlled airspace, an aircraft must have at minimum', '["VOR receiver, altimeter, gyroscopic pitch and bank indicator, and heading indicator", "GPS, altimeter, transponder, and communication radio", "Only an IFR-certified GPS and communication radio"]', 0, 'FAR 91.205(d) requires specific equipment for IFR flight including generators, gyroscopic rate-of-turn indicator, altimeter, clock, attitude indicator, heading indicator, DME or ADF at FL240+, and more.'),
('IFR', 'Regulations', 'Fuel', 'For an IFR flight at night, fuel requirements state that you must have enough fuel to reach the destination, then fly to the alternate (if required), and then', '["30 minutes at normal cruise speed", "45 minutes at normal cruise speed", "60 minutes at normal cruise speed"]', 1, 'FAR 91.167 requires IFR flights to carry enough fuel to complete the flight to the destination, fly to the alternate (if required), and thereafter fly for 45 minutes at normal cruising speed.'),
('IFR', 'Procedures', 'Holds', 'Standard holding pattern turns are made', '["To the right, with one-minute straight legs", "To the left, with one-minute straight legs", "To the right, with two-minute straight legs above 14,000 feet"]', 0, 'Standard holding patterns use right-hand turns with one-minute straight legs at or below 14,000 feet MSL (1.5-minute legs above 14,000 feet). Non-standard holds use left-hand turns and will be depicted on the chart.'),
('IFR', 'Navigation', 'ILS', 'What does "localizer back course" refer to?', '["The opposite end approach using the localizer signal from the back of the antenna", "A secondary ILS frequency used for backup approaches", "The glideslope signal measured from the opposite direction"]', 0, 'A localizer back course approach uses the 180-degree reciprocal of the front course localizer signal. The sensing is reversed — left/right needle deflection is opposite. HSI/CDI must be interpreted carefully or set to the back course.'),
('IFR', 'Weather', 'Icing', 'Where is carburetor ice most dangerous during instrument flight?', '["During cruise at high altitude", "During approach when power is reduced and humidity may be high", "On the ground during runup"]', 1, 'Carburetor ice is especially dangerous during the approach phase when power is reduced to idle or near-idle for extended periods. Low power combined with moist conditions creates ideal carburetor icing conditions.'),
('IFR', 'Procedures', 'Approach', 'What is a Decision Altitude (DA) vs. a Minimum Descent Altitude (MDA)?', '["DA is used for precision approaches; MDA is used for non-precision approaches", "DA is used for non-precision approaches; MDA is used for precision approaches", "DA and MDA are interchangeable terms"]', 0, 'Decision Altitude (DA) is used on precision approaches (ILS, LPV). At DA, the pilot must decide to land or execute a missed approach. MDA is used on non-precision approaches and is the lowest altitude to which a pilot may descend before the MAP without visual reference.'),
('IFR', 'Regulations', 'Logging', 'Instrument flight time may be logged', '["Only in actual IMC conditions", "Only under a safety pilot in VMC", "In actual IMC or simulated IMC with a safety pilot under actual VMC"]', 2, 'FAR 61.51(g) allows instrument flight time to be logged when flying in actual instrument meteorological conditions (IMC) or when flying under simulated IMC (under a hood/foggles) with an appropriately rated safety pilot in the aircraft.'),
('IFR', 'Navigation', 'GPS', 'What does RAIM stand for and why is it important for IFR GPS operations?', '["Receiver Autonomous Integrity Monitoring — ensures GPS signals are reliable enough for navigation", "Radio Altitude Instrument Measurement — measures altitude", "Radar Altimeter Instrument Mode — backup navigation"]', 0, 'RAIM (Receiver Autonomous Integrity Monitoring) checks the integrity of GPS signals by cross-checking satellite data. If sufficient satellites or signal integrity are not available, RAIM provides a warning. GPS approaches require RAIM availability.'),
('IFR', 'Procedures', 'Approach', 'When may a pilot descend below the MDA on a non-precision approach?', '["At any time after passing the Final Approach Fix", "Only when the runway threshold, approach lights, or other runway environment is clearly visible and a normal descent rate can be maintained", "Any time after acquiring the VASI or PAPI"]', 1, 'FAR 91.175 states that a pilot may not operate below MDA unless: the aircraft is continuously in a position to make a normal landing, the flight visibility is not less than the published minimums, and the runway environment is clearly visible.'),
('IFR', 'Weather', 'Fronts', 'A warm front is characterized by', '["Fast-moving, line of severe thunderstorms", "Gradual lifting of air, producing extended areas of stratiform clouds and precipitation", "Rapid clearing after passage"]', 1, 'Warm fronts occur when warm air advances and overrides cooler air. The gradual lifting produces extensive layers of stratiform clouds and precipitation that can extend 200-300 miles ahead of the surface front.'),
('IFR', 'Navigation', 'Radar', 'When ATC provides radar vectors, the pilot', '["Retains responsibility for terrain and obstacle clearance unless below MVA or MIA", "Is relieved of all navigation responsibilities", "Should follow vectors even if they appear to conflict with published minimums"]', 0, 'Even when receiving radar vectors, the pilot in command retains responsibility for terrain and obstacle clearance. ATC vectors are only guaranteed safe if the aircraft is at or above the Minimum Vectoring Altitude (MVA) or Minimum IFR Altitude (MIA).'),
('IFR', 'Procedures', 'Alternate', 'If the 1-2-3 rule is met (weather at destination within 1 hour before/after ETA is forecast to be at least 2000-3), an alternate is', '["Not required", "Required but any airport within 200nm qualifies", "Required and must have an instrument approach"]', 0, 'FAR 91.169 states that if, for at least 1 hour before and after the ETA, the ceiling will be at least 2,000 feet and visibility at least 3 statute miles, an alternate airport is NOT required.'),
('IFR', 'Regulations', 'Currency', 'To remain IFR current, a pilot must have within the preceding 6 calendar months', '["6 instrument approaches, holding procedures, and intercepting and tracking courses", "3 instrument approaches and 1 hour of actual IMC", "5 hours of instrument time and 3 approaches"]', 0, 'FAR 61.57(c) requires that to act as PIC under IFR, a pilot must have within the preceding 6 calendar months performed and logged 6 instrument approaches, holding procedures, and intercepting and tracking courses using navigation systems.'),

-- CPL Questions
('CPL', 'Regulations', 'Commercial Operations', 'A commercial pilot may act as pilot in command of an aircraft for compensation or hire if', '["The pilot has a commercial certificate with appropriate category, class, and type ratings", "The pilot has an ATP certificate", "The pilot has 500 hours total time"]', 0, 'A commercial pilot certificate authorizes the holder to act as PIC of aircraft for compensation or hire in the appropriate category and class, subject to any applicable endorsements and instrument currency requirements.'),
('CPL', 'Aerodynamics', 'Performance', 'During a commercial maneuver such as a chandelle, the objective is to', '["Gain maximum altitude while making a 180-degree heading change, completing the turn at minimum controllable airspeed", "Make a steep 360-degree climbing turn", "Simulate an engine failure on departure"]', 0, 'A chandelle is a climbing 180-degree turn that combines a constant bank turn with a climbing pitch attitude. The goal is to complete the 180-degree turn at minimum controllable airspeed (just above stall) to demonstrate maximum performance coordination.'),
('CPL', 'Regulations', 'Logbook', 'Commercial pilot candidates must have logged at minimum', '["250 hours total flight time", "1500 hours total flight time", "500 hours total flight time"]', 0, 'FAR 61.129 requires a minimum of 250 hours total flight time for a commercial pilot certificate in airplanes, including specific requirements for PIC time, cross-country time, instrument time, and night time.'),
('CPL', 'Aerodynamics', 'Lazy Eight', 'During a lazy eight maneuver, the bank angle and pitch reach their maximum', '["At the same point in the maneuver", "At different points — pitch maximum at 45 degrees of turn, bank maximum at 90 degrees", "Both at 180 degrees of turn"]', 1, 'In a lazy eight, the maximum pitch attitude is reached at the 45-degree point of the turn, and the maximum bank angle is reached at the 90-degree point. The maneuver is symmetrical through 180 degrees of turn.'),
('CPL', 'Systems', 'Complex Aircraft', 'A complex aircraft is defined as an aircraft that has', '["Retractable landing gear, flaps, and a controllable-pitch propeller", "More than 200 horsepower", "Turbine engines"]', 0, 'A complex aircraft is defined in FAR 61.1 as one that has all of the following: retractable landing gear, flaps, and a controllable-pitch propeller (or turbine engine). An endorsement is required to act as PIC.'),
('CPL', 'Regulations', 'Part 135', 'Commercial operations under FAR Part 135 require', '["An operations specification from the FAA and specific crew qualifications", "Only a commercial pilot certificate", "A minimum of 2 flight crew for all operations"]', 0, 'Part 135 (commuter and on-demand) air carrier operations require an Air Carrier Certificate with operations specifications from the FAA. Pilots must meet specific minimum flight time requirements and training standards.'),
('CPL', 'Aerodynamics', 'Steep Turns', 'During a commercial steep turn (50-degree bank), load factor increases and stall speed', '["Decreases because of the increased lift", "Increases because of the higher load factor", "Remains constant because airspeed is maintained"]', 1, 'In a steep turn, load factor increases significantly. Since stall speed increases proportionally to the square root of the load factor, a 50-degree bank creates a load factor of about 1.56 Gs, increasing stall speed by approximately 25%.'),
('CPL', 'Regulations', 'Night Operations', 'For commercial operations, night is defined as', '["1 hour after sunset to 1 hour before sunrise", "The period between evening civil twilight and morning civil twilight", "Any time when the sun is below the horizon"]', 1, 'For Part 135 and Part 121 commercial operations, night is defined as the time between evening civil twilight and morning civil twilight. This differs slightly from the FAR 1.1 definition used for currency purposes.'),
('CPL', 'Aerodynamics', 'High Altitude', 'At high altitudes, a turbocharged engine maintains sea-level manifold pressure up to its critical altitude because', '["The turbocharger compresses intake air to compensate for lower atmospheric pressure", "The engine runs on a richer mixture at altitude", "Propeller efficiency increases at altitude"]', 0, 'A turbocharger uses exhaust gases to drive a compressor that pressurizes intake air. This maintains sea-level equivalent manifold pressure and power output up to the engine''s critical altitude, above which power begins to decrease.'),
('CPL', 'Regulations', 'Commercial Privileges', 'A commercial pilot with instrument rating may carry passengers for hire', '["On IFR flights when IFR current and proficient", "Only if the aircraft is equipped with an autopilot", "Only if a co-pilot is present"]', 0, 'A commercial pilot with an instrument rating and current IFR proficiency may carry passengers for hire on IFR flights. FAR Part 91 operations with a commercial certificate allow single-pilot IFR operations without a co-pilot requirement.'),

-- ATP Questions
('ATP', 'Regulations', 'Part 121', 'Under Part 121, the minimum rest period for a pilot on a domestic operation is', '["8 consecutive hours free from duty", "9 consecutive hours free from duty", "10 consecutive hours, providing an 8-hour sleep opportunity"]', 2, 'Under the FAA''s current Part 121 rest rules (effective 2014), the minimum rest period is 10 consecutive hours, which must provide the opportunity for 8 hours of uninterrupted sleep.'),
('ATP', 'Regulations', 'ATP Certificate', 'An Airline Transport Pilot certificate requires a minimum of', '["1,500 hours total flight time (or 1,000 hours with a military background)", "2,000 hours total flight time", "1,000 hours total flight time for all applicants"]', 0, 'FAR 61.159 requires 1,500 hours total flight time for an ATP certificate. However, graduates of an approved aviation university program may qualify with 1,000 hours, and military pilots may qualify with as few as 750 hours.'),
('ATP', 'Aerodynamics', 'High Speed', 'At high Mach numbers, what phenomenon occurs that can cause loss of control authority?', '["Mach tuck — the center of pressure moves aft, causing a nose-down tendency", "Mach buffet — violent airframe vibration", "Dutch roll — oscillation in roll and yaw"]', 0, 'Mach tuck occurs when shock waves form on the wing, causing the center of lift to shift aft. This creates a nose-down pitching moment that increases with speed. Aircraft are designed with Mach trim systems to compensate.'),
('ATP', 'Systems', 'Pressurization', 'If cabin pressurization is lost at FL350, time of useful consciousness (TUC) is approximately', '["30 seconds to 1 minute", "3-5 minutes", "10-15 minutes"]', 0, 'At FL350, time of useful consciousness after rapid decompression is approximately 30-60 seconds. At FL250 it is 3-5 minutes. At FL180 it is 30 minutes or more. Supplemental oxygen must be donned immediately.'),
('ATP', 'Regulations', 'CRM', 'Crew Resource Management (CRM) training focuses on', '["Effective use of all available resources including crew members, automation, and information to ensure safe flight", "Simulator training for emergency procedures only", "Captain authority and command decision-making"]', 0, 'CRM training addresses the effective utilization of all resources — human, hardware, and information — available to flight crews to ensure safe and efficient operations. Key elements include communication, situational awareness, decision-making, and workload management.'),
('ATP', 'Regulations', 'Part 121', 'Under Part 121, a captain must be qualified in', '["The specific aircraft make, model, and series by type certificate", "Any aircraft in the same weight category", "Any transport category aircraft with an ATP certificate"]', 0, 'Part 121 captains must hold a type rating in the specific aircraft make and model series. ATP certificate holders must have completed all required training and checking for the specific type.'),
('ATP', 'Systems', 'TCAS', 'When a TCAS Resolution Advisory (RA) is issued, the crew should', '["Follow the RA immediately, then notify ATC", "Confirm with ATC before following the RA", "Follow the RA only if it agrees with ATC instructions"]', 0, 'TCAS RAs must be followed immediately without awaiting ATC clearance. The crew should notify ATC of the maneuver as soon as practicable. TCAS RAs take priority over ATC instructions. Failure to comply with a TCAS RA has been a contributing factor in mid-air collisions.'),
('ATP', 'Aerodynamics', 'V Speeds', 'V1 (Takeoff Decision Speed) represents', '["The maximum speed at which the takeoff can be rejected and the aircraft stopped within the remaining runway", "The minimum control speed with critical engine inoperative", "The rotation speed for normal takeoffs"]', 0, 'V1 is the critical engine failure recognition speed above which the takeoff should be continued even if an engine fails. Below V1, there is sufficient runway remaining to stop. Above V1, continuing the takeoff is the correct procedure.'),
('ATP', 'Systems', 'Hydraulics', 'In a large transport category aircraft, what is typically powered by the hydraulic system?', '["Flight controls, landing gear, and brakes", "Only the landing gear and brakes", "Only the flight controls"]', 0, 'Transport category aircraft hydraulic systems typically power flight control surfaces, landing gear extension/retraction, wheel brakes, thrust reversers, and nose wheel steering. Multiple independent hydraulic systems provide redundancy.'),
('ATP', 'Regulations', 'ETOPS', 'ETOPS (Extended-range Twin-engine Operational Performance Standards) approval allows', '["Twin-engine aircraft to fly routes that take them more than 60 minutes from a diversion airport", "All aircraft to extend over-water operations", "Only widebody jets to fly transoceanic routes"]', 0, 'ETOPS allows twin-engine airliners to fly routes that would take them more than 60 minutes (at single-engine cruise speed) from an adequate diversion airport. Standard ETOPS approval is for 120 or 180 minutes; some aircraft are approved for 330 minutes.'),
('ATP', 'Aerodynamics', 'Swept Wing', 'The primary advantage of wing sweep on a high-speed jet is', '["It delays the onset of compressibility effects by reducing the effective Mach number seen by the wing", "It improves low-speed handling characteristics", "It reduces structural weight"]', 0, 'Wing sweep delays the critical Mach number by reducing the component of airflow perpendicular to the leading edge. This allows the aircraft to fly at higher speeds before shock waves form, delaying drag rise and compressibility effects.');
